// Regenerates the browser's copy of the OAuth scope from the single source in
// typescript-helpers/lib/oauth-scope. The browser cannot import that package,
// so the string is emitted here rather than written by hand anywhere.
//
// Exits non-zero when the committed file is out of sync, so a stale scope fails
// CI instead of silently shipping.

import { REQUESTER_OAUTH_SCOPE } from "@publicdomainrelay/oauth-scope";

const path = new URL("../web/generated/oauth-scope.js", import.meta.url).pathname;

const generated = [
  "// AUTO-GENERATED by scripts/generate-web-scope.ts -- DO NOT EDIT.",
  "// Single source: typescript-helpers/lib/oauth-scope/mod.ts.",
  `export const OAUTH_SCOPE = ${JSON.stringify(REQUESTER_OAUTH_SCOPE.join(" "))};`,
  "",
].join("\n");

const existing = await Deno.readTextFile(path).catch(() => null);
if (existing === generated) {
  console.log("web/generated/oauth-scope.js is in sync");
} else {
  await Deno.mkdir(new URL("../web/generated/", import.meta.url).pathname, { recursive: true });
  await Deno.writeTextFile(path, generated);
  if (existing === null) {
    console.log("wrote web/generated/oauth-scope.js");
  } else {
    console.error("web/generated/oauth-scope.js was out of sync with @publicdomainrelay/oauth-scope — rewritten; commit the change");
    Deno.exit(1);
  }
}
